# CAREFUL: yaml is super sensitive to spaces - don't use tabs
# The generated maps are not convolved with any window function or mask,
# this will be done when measuring the power spectra
# Assumes that all maps are either scalar (spin=0) or tensor (spin=2)
# The probes should be ordered such that the spin 0 fields are first,
# followed by the spin 2 fields
# # Assumes that all B-modes of all spin 2 fields are zero

mode: curved
path2outputdir: '/global/cscratch1/sd/sferraro/SOxpipe/input_cl/sims_grf/mocks_gks_lsstxso_curved'
nrealiz: 2
probes: ['g', 'kcmb', 'shear']
spins: [0, 0, 2]
nside: 1024
lmax: 9000 # should be a fraction of  

path2cls: ['/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_gg.txt', '/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_gk.txt', 
'/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_gs.txt', 
'/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_kk.txt', '/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_ks.txt', 
'/global/cscratch1/sd/sferraro/SOxpipe/input_cl/cl_ss.txt']

noisemodel: theory   # None if no noise wanted
path2noisecls: ['/global/cscratch1/sd/sferraro/SOxpipe/input_cl/ncl_gg.txt', '/global/cscratch1/sd/sferraro/SOxpipe/input_cl/ncl_kk.txt', 
'/global/cscratch1/sd/sferraro/SOxpipe/input_cl/ncl_ss.txt']
